### PR TITLE
Restructure file check methodology and add parallelism.

### PR DESCRIPTION
**Pull request by aslicerh**
Use object structure for file types.
Use LINQ for array searches.
Use Parallel Tasks for file ForEach.

### CODE REVIEW

**Comment by aslicerh** [comment]
By the way, feel free to ignore this PR. It uses a style that I like but that I understand some people might not. Also, I did this because I was itching to do some C# work and this looked like fun. Which it was.

If nothing else though, look at that line using the parallel foreach on the file searches. It cut my runtime down a lot, even running it in a container.
```
bash-4.2# time dotnet new/bin/Debug/netcoreapp2.0/LicenseCheck.dll /opt/tmp/ > /dev/null 2>&1       
real    1m39.894s
user    3m45.604s
sys     0m15.886s

bash-4.2# time dotnet orig/bin/Debug/netcoreapp2.0/LicenseCheck.dll /opt/tmp/ > /dev/null 2>&1
real    4m24.314s
user    3m34.371s
sys     0m4.808s
```

**Comment by omajid** [comment]
Sorry for breaking your patch. If you can fix it up, I will happily merge it!

**Comment by aslicerh** [comment]
The time savings from the parallelization is still there.

```
bash-4.2# time dotnet new/LicenseCheck/bin/Debug/netcoreapp2.0/LicenseCheck.dll /opt/tmp/ > /dev/null 2>&1

real    1m43.077s
user    3m51.341s
sys     0m17.818s

bash-4.2# time dotnet orig/LicenseCheck/bin/Debug/netcoreapp2.0/LicenseCheck.dll /opt/tmp/ > /dev/null 2>&1

real    4m4.719s
user    3m2.578s
sys     0m5.870s
```

**Comment by omajid** [comment]
Thanks!

**Pull request merged**
